version: '3.9'

services:
  historyusers:
    container_name: history
    hostname: history
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "3050:3050"
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm i && npm run start:dev"
    networks:
      - backend-network

networks:
  backend-network:
    external:
      name: db_default
